### PR TITLE
Improve highlighting in reports

### PR DESCRIPTION
**Pull request by cpitclaudel**
* Add a button face and enable clicking on register report lines
* Use ledger's own highlighting in report buffers

Supersedes GH-68? CC @jabranham

### CODE REVIEW

**Comment by jabranham** [comment]
Nice! This is definitely better than #68 since it also fixes #20, something @akater has been working on, I believe. Can you also update the description of ledger-font-report-clickable-face in doc/ledger-mode.texi line 1082?

**Comment by cpitclaudel** [comment]
Done, thanks for the pointer :)

**Comment by cpitclaudel** [comment]
Btw, what do you think of the following additional patch?

```diff
diff --git a/ledger-report.el b/ledger-report.el
index 7efde22..2ceb69e 100644
--- a/ledger-report.el
+++ b/ledger-report.el
@@ -93,6 +93,11 @@ ledger-report-use-native-highlighting
   :type 'boolean
   :group 'ledger-report)
 
+(defcustom ledger-report-auto-width t
+  "When non-nil, tell ledger about the width of the report window."
+  :type 'boolean
+  :group 'ledger-report)
+
 (defcustom ledger-report-use-header-line nil
   "When non-nil, indicate the report name and command in the `header-line'
 instead of in the buffer."
@@ -379,6 +384,8 @@ ledger-do-report
       (setq cmd (concat cmd " --prepend-format='%(filename):%(beg_line):'")))
     (when ledger-report-use-native-highlighting
       (setq cmd (concat cmd " --color --force-color")))
+    (when ledger-report-auto-width
+      (setq cmd (concat cmd (format " --columns %d" (window-width)))))
     (shell-command cmd t nil)
     (when ledger-report-use-native-highlighting
       (ansi-color-apply-on-region data-pos (point-max)))
```

**Comment by akater** [comment]
Looks like this patch merely appends formatting options to the tail of command string. This won't work well for commands which contain multiple calls to ledger which is why I used regex in my approach; see example of multi-call command here https://github.com/ledger/ledger-mode/pull/61#issuecomment-356431289 I wouldn't call this a corner case, as I myself use a custom report like that one daily, more or less. Certainly useful for multicurrency journals.

**Comment by cpitclaudel** [comment]
> Looks like this patch merely appends formatting options to the tail of command string. This won't work well for commands which contain multiple calls to ledger which is why I used regex in my approach; see example of multi-call command here #61 (comment) I wouldn't call this a corner case, as I myself use a custom report like that one daily, more or less. Certainly useful for multicurrency journals.

Great point. What do you think of the fix I just pushed?  The idea is to include these arguments into the expansion of `%(binary)`

**Comment by akater** [comment]
Clément Pit-Claudel <notifications@github.com> writes:

> Great point. What do you think of the fix I just pushed?  The idea is to include these arguments into the expansion of `%(binary)`
This is of course much cleaner than what I suggested. I can't review all
of it atm but as soon as it does well for your everyday needs, I
will cancel my pull request, proposing to merge yours instead.

One minor note: your patch deals both with highlighting and report
width. I tested my report width patch in both tty Emacs and X (GUI)
Emacs, and found that it required a little adjustment: see line 363 here
https://github.com/ledger/ledger-mode/compare/master...akater:width-auto-adjustment#diff-281a2bc801a5ecafb82d5fa789415bb2R363

Not sure if this is reproducible but if you care about tty Emacs, you
might want to take a look.

**Comment by cpitclaudel** [comment]
> This is of course much cleaner than what I suggested. I can't review all
of it atm but as soon as it does well for your everyday needs, I
will cancel my pull request, proposing to merge yours instead.

Thanks! Hopefully we can get an extra review before merging :)

>  One minor note: your patch deals both with highlighting and report width. I tested my report width patch in both tty Emacs and X (GUI) Emacs, and found that it required a little adjustment: see line 363 here master...akater:width-auto-adjustment#diff-281a2bc801a5ecafb82d5fa789415bb2R363

I actually left the report width part out.  I originally didn't see your PR, but I took it out once I did :) I'll reintegrate it, but I'll proper credits.

> found that it required a little adjustment: see line 363 here master...akater:width-auto-adjustment#diff-281a2bc801a5ecafb82d5fa789415bb2R363

I left a comment on the PR.  I think using window-width for everything is good, and it should need a -1 everywhere.

**Comment by cpitclaudel** [comment]
> I'll reintegrate it, but I'll proper credits.

Done.  I had to push an extra commit on top of that to make sure that refreshing the report window with `g` would recompute the window width.

**Comment by akater** [comment]
Great. Maybe you need to `(require 'ansi-color)` somewhere.

**Comment by cpitclaudel** [comment]
> 
> Great. Maybe you need to (require 'ansi-color) somewhere.

Yes, excellent point.

**Comment by purcell** [comment]
Looks good to me - merged!

**Comment by purcell** [comment]
May I suggest to @jwiegley / @enderw88 that we add @cpitclaudel as a collaborator on this repo please?

**Comment by jwiegley** [comment]
I've invited you and he to become part of the Ledger Hackers group, which will give you full admin rights to all three related repositories.

**Comment by purcell** [comment]
Thanks @jwiegley - for a while now I've been following your example of handing out the commit bit liberally.

**Comment by akater** [comment]
@cpitclaudel Just one minor thing I forgot to mention. The expression `(- window-width 1)` is mentioned twice in the current version of legder-report.el. In both cases it is computed for essentially the same purpose. I'd say it's a clear violation of D.R.Y. to leave these two as is; better to define a function.

**Pull request merged**
