### PR TITLE
Fix shifting month beyond January/December (#128)

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by jabranham** [comment]
Yup, seems to work for me. Thanks for the quick fix!

**Comment by DamienCassou** [comment]
This is ready to be merged then.

**Comment by DamienCassou** [comment]
Can someone please merge this? The fix is simple and tested.

**Comment by DamienCassou** [comment]
John Wiegley <notifications@github.com> writes:
> Merged #129 into master.

Thank you

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Pull request merged**
