### PR TITLE
Allow pedantic account completion

### PR DESCRIPTION
**Pull request by jabranham**
Fixes bug #101

### CODE REVIEW

**Comment by purcell** [comment]
I feel like this is only a workaround for #101, and not yet an actual fix, which would be preferable. I think the regexes used to identify accounts probably need to be tightened up, or scoped more carefully.

**Comment by jabranham** [comment]
You're right, fix was a bad word choice on my part.

Is there a reason we don't just ask ledger for the accounts? Seems easier
than trying to figure out regexs....

**Comment by jabranham** [comment]
This is along the lines of what I was thinking. (ignore the `(if nil ... ` part, I just kept it while testing it out:

```elisp
(defun ledger-accounts-list-in-buffer ()
  "Return a list of all known account names in the current buffer as strings.
Considers both accounts listed in postings and those declared with \"account\" directives."
  (save-excursion
    (goto-char (point-min))
    (let (results)
      (if nil (progn
                (while (re-search-forward (if ledger-accounts-be-pedantic
                                              ledger-account-directive-regex
                                            ledger-account-name-or-directive-regex) nil t)
                  (setq results (cons (match-string-no-properties 2) results))))
        (setq results (split-string
                       (shell-command-to-string
                        (concat "ledger -f " (buffer-file-name) " accounts" ))
                       "\n")))
      (sort (cl-delete-duplicates results :test 'string=)
            #'ledger-string-greaterp))))
```

**Comment by purcell** [comment]
> Is there a reason we don't just ask ledger for the accounts? Seems easier than trying to figure out regexs....

Yes. `ledger accounts` doesn't list accounts declared with `account` directives, or in included files IIRC.

Re. the proposed change, I don't think the logic for finding accounts for completion purposes is modal in any way, so I feel like switching between two regexes based on a flag isn't the right approach.

**Comment by jabranham** [comment]
OK, I'll close this then while we think of another way to solve the issue. 

People who want this fix now before a proper fix is out can use `(setq ledger-account-name-or-directive-regex ledger-account-directive-regex)`.

**Comment by DamienCassou** [comment]
Please check if https://github.com/ledger/ledger-mode/pull/124 fixes the issue.

**Pull request closed without merging**
