### PR TITLE
Fix ledger string to number

### PR DESCRIPTION
**Pull request by felipebalbi**
With these two patches, I have reconciliation working with decimal comma.

### CODE REVIEW

**Comment by enderw88** [comment]
I need to understand the purpose of the [] in the expression.  I have tested the previous code with decimal-comma set and it worked.  Was it not working for you?

**Comment by felipebalbi** [comment]
@enderw88 [.] is similar to \. I'm telling regexp to treat . as a character, not a field that matches any single character. As described in the commit log, I had every character removed from the string and always got "pending" set to 0. Everything worked fine when I reversed all numbers to decimal period, though.

**Comment by purcell** [comment]
> [.] is similar to . I'm telling regexp to treat . as a character, not a field that matches any single character

You should ideall use `"\\."` instead here: the `\\` in a string expands to a literal `\`, which escapes the following special regexp character, `.` in this case.

**Comment by thdox** [comment]
In this pull request, you say that "With these two patches, I have reconciliation working with decimal comma". 

I live in France, the decimal separator is comma. Reconciliation is working fine for my use cases. Moreover, in the regression tests, there are the tests `ledger-reconcile/test-008` and `ledger-reconcile/test-012` that are passing with comma as decimal separator.

Do you have an example of a ledger file that is failing when reconciliation is launched?

**Pull request merged**
