### PR TITLE
ledger-mode Travis integration

### PR DESCRIPTION
**Pull request by thdox**
I have added integration with Travis, and some regress tests for ledger-mode.

The total is something like 100 commits. I have tested the concatenation of those 100 commits in Travis, using private repository, and it worked successfully. 

I will probably propose 3 pull requests, as locally I have worked on three branches. This is the **first** pull request. This one is relatively safe to merge, as it only adds new files, without any interaction with existing files. Once this first PR accepted, I need to rebase my other branches and do some fixup before submitting other branches.

The collaborator accepting this pull request need to **enable travis integration** of ledger-mode. This can be done via https://travis-ci.org/profile/ledger

### CODE REVIEW

**Comment by afh** [comment]
Great work 👍

**Comment by purcell** [comment]
Looks really good! Who has admin rights here, and can enable Travis integration?

**Comment by enderw88** [comment]
I can't do it.  It looks like it actually wants to use the ledger project integration.  Should ledger-mode be complete different?

**Comment by thdox** [comment]
I just enabled the Travis integration for ledger-mode.
As @afh + @purcell  + @enderw88 looks happy with this Pull Request #5, I will merge it.

**Pull request merged**
