### PR TITLE
Shorten docstrings

### LINKED ISSUE #335: Docstrings need shortening for 28.1 byte compiler
Too-long docstrings now cause compilation issues, as of Emacs 28.1: we'll need to go through all the docstrings and shorten them. Noting this here as a collective to-do.

### PR DESCRIPTION
**Pull request by purcell**
Fixes #335

### CODE REVIEW

**Comment by purcell** [comment]
Ledger snapshot builds are still failing (as before), but otherwise this gets the CI working again, so will merge.

**Comment by bcc32** [comment]
I think e8661a1 is broken, shouldn't it be something like the following?

```elisp
(defun ledger-exec-success-p (exit-code ledger-output-buffer)
  "Return non-nil if EXIT-CODE and LEDGER-OUTPUT-BUFFER indicate success."
  (and (zerop exit-code)
       (with-current-buffer ledger-output-buffer
         (goto-char (point-min))
         (not (and (> (buffer-size) 1) (looking-at (regexp-quote "While")))))))
```

Right now, it's returning `t` when `exit-code` is 1.

**Comment by purcell** [comment]
@bcc32 Yes, oops, thanks — fix pushed as above.

**Comment by purcell** [comment]
Super cool that the tests passed anyway... 😬

**Pull request merged**
