### PR TITLE
Previous/next month

### PR DESCRIPTION
**Pull request by DamienCassou**
This PR makes it possible to change a report's currently visible month by using `M-p` and `M-n`.

### CODE REVIEW

**Comment by DamienCassou** [comment]
ping

**Comment by purcell** [comment]
Looks good, thanks.

**Comment by jabranham** [comment]
This doesn't seem to work if the next/previous month is in a different year, though, right? For me if I try to go from January 2018 to December 2017 --- it tries to change it from `2018-1` to `2018-0`.

**Comment by DamienCassou** [comment]
@jabranham you are obviously right :-). Sorry about that: https://github.com/ledger/ledger-mode/issues/128

**Pull request merged**
